load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_rust",
    sha256 = "8a2052e8ec707aa04a6b9e72bfc67fea44e915ecab1d2d0a4835ad51c2410c36",
    strip_prefix = "rules_rust-b16c26ba5faf1c58ebe94582afd20567ce676e6d",
    urls = [
        "https://github.com/bazelbuild/rules_rust/archive/b16c26ba5faf1c58ebe94582afd20567ce676e6d.tar.gz",
    ],
)

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories(
    edition = "2021",
    include_rustc_srcs = True,
    version = "1.57.0",
)

load("@rules_rust//crate_universe:bootstrap.bzl", "crate_universe_bootstrap")

crate_universe_bootstrap()

load("@rules_rust//crate_universe:defs.bzl", "crate", "crate_universe")

crate_universe(
    name = "crates",
    packages = [
        crate.spec(
            name = "value-bag",
            semver = "=1.0.0-alpha.7",
        ),
    ],
    resolver = "@rules_rust_crate_universe_bootstrap//:crate_universe_resolver",
    supported_targets = [
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
)

load("@crates//:defs.bzl", "pinned_rust_install")

pinned_rust_install()
